title: "Dr. Geetanjali Mahamunkar"
email: "gsmahamunkar@dbatu.ac.in"
description: >- 
  Remote Sensing | GIS | Deep Learning | Educator | Researcher
baseurl: "" 
url: "https://gsmahamunkar.github.io"
theme: minima
plugins:
  - jekyll-feed
future: false
social_links:
  - platform: linkedin
    user_url: https://www.linkedin.com/in/geetanjali-mahamunkar
  - platform: orcid
    user_url: https://orcid.org/0000-0002-8043-097X
  - platform: google-scholar
    user_url: https://scholar.google.com/citations?user=I8fsgUAAAAAJ&hl=en
