title: "Dr. Geetanjali Mahamunkar"
email: "gsmahamunkar@dbatu.ac.in"
description: >- 
  Remote Sensing | GIS | Deep Learning | Educator | Researcher
baseurl: "" 
url: "https://gsmahamunkar.github.io"
theme: minima
plugins:
  - jekyll-feed
future: false

social_links:
  - platform: linkedin
    user_url: https://www.linkedin.com/in/geetanjali-mahamunkar
  - platform: orcid
    user_url: https://orcid.org/0000-0002-8043-097X
  - platform: google-scholar
    user_url: https://scholar.google.com/citations?user=I8fsgUAAAAAJ&hl=en
# Additional styling and enhancements
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Dr. Geetanjali Mahamunkar"

markdown: kramdown
highlighter: rouge

# Google Fonts and site style enhancements
sass:
  style: compressed

# Add a favicon if needed
favicon: /favicon.ico

# Banner image config (optional for use in index.md)
banner:
  image: "/assets/images/banner.jpg"
  alt: "Remote Sensing Visualization"
  show: true

# Theme customization: custom CSS
include:
  - assets/css/custom.css
  
header_pages:
  - index.md
  - about.md
  - cv.md
  - teaching.md
  - research.md
  - publications.md
  - blog.md

