title: "Dr. Geetanjali Sameer Mahamunkar"
email: "your.email@example.com"
description: >-
  Lecturer | Researcher | GIS & Remote Sensing | Deep Learning for Geospatial Data

baseurl: "" 
url: "https://gsmahamunkar.github.io" 
github_username: gsmahamunkar

# Social Links
linkedin_username: geetanjali-mahamunkar
google_scholar_id: I8fsgUAAAAAJ
orcid_id: 0000-0002-8043-097X

markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
